### ISSUE TITLE
Show support ?

### ISSUE THREAD

**Issue by Write** [jmxd/Kometa#4]
Hi, thanks for your work.
It's amazing for movies.
I tried to apply it for Shows library, but it doesn't seem to work.

Do you plan to add support for TV Shows, or perhaps I misconfigured something ? 
Thanks a lot.

**Comment by Museberg** [comment]
I am also having issues with TV Shows. I can get it to overlay Media Info on each episode but Audience Rating does not work.
This is my config:
```
TV Shows:
  remove_overlays: false             
  overlay_files:
    - file: config/overlays/media_info.yml
      template_variables:
        builder_level: episode
    - file: config/overlays/audience_rating.yml
      template_variables:
        builder_level: episode
```          

Looking at the log it only considers the TV Show posters for audience rating.

**Comment by Museberg** [comment]
> Generally speaking i would not advise to apply overlays to individual episodes as that can take an extremely long amount of time.

Oh, I know. Took around 10 hours for the first run of 14K episodes. Then about 2 hours the following run. I am fine with that.
Thanks for getting back to us and good to hear you are working on it

**Comment by Write** [comment]
> > Hi, thanks for your work. It's amazing for movies. I tried to apply it for Shows library, but it doesn't seem to work.
> > Do you plan to add support for TV Shows, or perhaps I misconfigured something ? Thanks a lot.
> 
> Media info works for shows, use `builder_level: season` to apply it to season posters and `builder_level: episode` to apply it to each individual episode. Without `builder_level` it will be applied to the show poster itself. What exactly isn't working?
> 
> > I am also having issues with TV Shows. I can get it to overlay Media Info on each episode but Audience Rating does not work.
> 
> The audience_rating overlay does not support the `builder_level` variable, so it can only be applied to shows & movies. This is kind of an oversight though, i'll look into making that possible.
> 
> Generally speaking i would not advise to apply overlays to individual episodes as that can take an extremely long amount of time.

At first, I tried the same as for movies : 

```
    overlay_files:
      - file: config/jmxd_overlays/media_info.yml
      - file: config/jmxd_overlays/audience_rating.yml
```

But that wouldn't work do anything, even though in the log it seemingly seems to apply the overlay with logs such as 
" DigitalPlus Overlay | X | South Park Season 22"

I now just tried this config, I tried to add "reapply_overlays" just in case.

```
    overlay_files:
      - remove_overlays: false  
      - reapply_overlays: true 
      - file: config/jmxd_overlays/media_info.yml
        template_variables:
          builder_level: season
      - file: config/jmxd_overlays/audience_rating.yml
        template_variables:
          builder_level: season
```

The console result seems the same , as if it was applied successfully, but nothing changed in my library, there's no overlay at all, either on the whole show or on a single season
![shot on 2024-June-13@20h05(54)](https://github.com/jmxd/Kometa/assets/541722/4d1de5e4-d66d-44b1-a8a0-3ac9f766ae50)


I do have an error after that : 


![shot on 2024-June-13@20h06(35)](https://github.com/jmxd/Kometa/assets/541722/ce4956eb-c991-4913-b26c-95c695fa117c)

**Comment by Write** [comment]
It's getting better now,

config : 

``
    overlay_files:
      - remove_overlays: false 
      - reapply_overlays: true 
      - file: config/jmxd_overlays/media_info.yml
        template_variables:
          builder_level: season
      - file: config/jmxd_overlays/audience_rating.yml
        template_variables:
          builder_level: season
      - file: config/jmxd_overlays/media_info.yml
      - file: config/jmxd_overlays/audience_rating.yml
  ```

And the result is : 

![shot on 2024-June-13@21h44(37)](https://github.com/jmxd/Kometa/assets/541722/2555f31d-6dcf-4548-9fe9-fa4e15196c45)

**Comment by Write** [comment]
I tried to remove all overlays, stopping Kometa, and then re-running the script. It seems that all main poster for Shows have still the rating hidden under the black shadow, this might be a fixable issue ?

Works fine on movie.

**Comment by Write** [comment]
I'm just dumb. Closing this.

```
    overlay_files:
      - file: config/jmxd_overlays/media_info.yml
      - file: config/jmxd_overlays/audience_rating.yml
```

It enough. No idea why it behaved like that.
